/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c2c6d4",
        "secondary-container": "#dce0e1",
        "tertiary-fixed": "#ffdbcb",
        "on-secondary-container": "#5f6364",
        "on-primary-container": "#c8daff",
        "surface-tint": "#005db6",
        "inverse-surface": "#26323b",
        "tertiary-container": "#9f4300",
        "surface-container-low": "#ebf5ff",
        "tertiary-fixed-dim": "#ffb691",
        "on-secondary-fixed-variant": "#434849",
        "error": "#ba1a1a",
        "secondary-fixed": "#dfe3e4",
        "primary": "#00478d",
        "background": "#f6faff",
        "tertiary": "#793100",
        "primary-fixed": "#d6e3ff",
        "inverse-on-surface": "#e6f2ff",
        "on-primary-fixed-variant": "#00468c",
        "on-tertiary-fixed-variant": "#793100",
        "on-tertiary-container": "#ffcfb9",
        "secondary": "#5a5f60",
        "outline": "#727783",
        "primary-fixed-dim": "#a9c7ff",
        "surface-container-high": "#ddeaf6",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f6faff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#001b3d",
        "on-background": "#111d25",
        "on-secondary": "#ffffff",
        "surface-dim": "#cfdce8",
        "secondary-fixed-dim": "#c3c7c8",
        "on-error-container": "#93000a",
        "surface": "#f6faff",
        "surface-container-highest": "#d7e4f0",
        "on-primary": "#ffffff",
        "on-surface": "#111d25",
        "surface-variant": "#d7e4f0",
        "on-secondary-fixed": "#181c1d",
        "on-surface-variant": "#424752",
        "on-tertiary-fixed": "#341100",
        "surface-container": "#e3effc",
        "inverse-primary": "#a9c7ff",
        "error-container": "#ffdad6",
        "primary-container": "#005eb8",
        "on-error": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "4px",
        "margin-mobile": "16px",
        "md": "16px",
        "sm": "8px",
        "xs": "4px",
        "margin-desktop": "48px",
        "lg": "24px",
        "xl": "32px",
        "gutter": "24px"
      },
      fontFamily: {
        "label-md": ["Public Sans"],
        "headline-lg-mobile": ["Public Sans"],
        "headline-sm": ["Public Sans"],
        "headline-lg": ["Public Sans"],
        "label-sm": ["Public Sans"],
        "body-sm": ["Public Sans"],
        "body-lg": ["Public Sans"],
        "body-md": ["Public Sans"],
        "headline-xl": ["Public Sans"],
        "data-display": ["Public Sans"],
        "headline-md": ["Public Sans"]
      },
      fontSize: {
        "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "14px", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-xl": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "data-display": ["48px", { "lineHeight": "48px", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}